import { Outfit } from "next/font/google";
import "./globals.css";
import 'animate.css';




const outfit = Outfit({
  subsets: ["latin"]
})

export const metadata = {
  title: "QurbaniHat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${outfit.className}h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
